### ISSUE TITLE
Weights are not getting saved.

### ISSUE THREAD

**Issue by sgangs** [deepgram/kur#100]
I'm running the speech example for Kur for about 3 hours now. It's in Epoch 15 (batch size of 16). However, I dont see where the weight is getting stored?

I believe the following line:
weights: &weights weights
means the weight would be stored in the /kur/examples/weight folder, right? However the same remains blank. Hence, I would like to know where is it (i,e, the weight & the model) getting stored.

Finally, how should I stop the training? It seems the training is meant to run for "infinity" no. of epochs.? I don't think "ctrl+c" is the way, right?

**Comment by scottstephenson** [comment]
They are hidden files. Do a `ls -a` and you'll see the weight files.

**Comment by chrisspen** [comment]
I'm not seeing weights either, dot-files or otherwise. Where are they saved? In the cwd or in ~/kur?
