### ISSUE TITLE
speech validating loss abnormal?

### ISSUE THREAD

**Issue by liaoweiguo** [deepgram/kur#16]
Epoch 70/inf, loss=6.643: 100%|████████| 2432/2432 [17:24<00:00,  2.29samples/s]
Validating, loss=806.257:  94%|█████████▍| 256/271 [00:40<00:02,  6.63samples/s]
Prediction: "lok h n v eon owlt im on nonaih"
Truth: "he was in a mood for music was he not"

training loss decreasing, while validating loss increasing, is that NOK?

**Comment by scottstephenson** [comment]
See #6  

The dataset that the stock speech.yml uses is small, so the model will only learn very basic language patterns (spaces, vowels and consonant ratio, etc). If you want much better performance then select the tarballs with larger dataset size (it will take up more space and take longer to train though!).
