### ISSUE TITLE
post processing code for tutorial from scratch has some error

### ISSUE THREAD

**Issue by EmbraceLife** [deepgram/kur#19]
The data type inside output.pkl from [tutorial from scratch: post processing](http://kur.deepgram.com/tutorial.html#post-processing) is [not both numpy.array](https://hyp.is/U1sWoPwpEeaNCfuITZEgOQ/kur.deepgram.com/tutorial.html), therefore, the code below is not working

I have ran the code myself, here is where goes wrong: 
<img width="914" alt="screen shot 2017-02-26 at 9 51 59 pm" src="https://cloud.githubusercontent.com/assets/8749266/23340248/e17c5860-fc6d-11e6-8419-bdc286f2bf72.png">

I managed to some code work, but not the others: 
```
# diff = numpy.abs(data['truth']['above'] - data['result']['above']) < 1 # original but not working
# I made some changes here, the accuracy is 98%, not 99.7%.
diff = np.array([np.abs(a - b[0]) for a, b in zip(data['truth']['above'], data['result']['above'])]) < 1
correct = diff.sum()
total = len(diff)
correct / total * 100

```

**Comment by ajsyp** [comment]
I isolated the commit that caused the tutorial to break (c0157db). I'll be pushing a fix when I have a minute.

**Comment by ajsyp** [comment]
Commit 5844dd3 should fix this. Please let me know if you see otherwise.
