### ISSUE TITLE
Error installing kur via pip (keras>=1.1.2 not found)

### ISSUE THREAD

**Issue by bharris47** [deepgram/kur#2]
Hi, I'm getting the following error when attempting to install kur via pip.

```
Could not find a version that satisfies the requirement keras>=1.1.2 (from kur) (from versions: 0.1.3)
No matching distribution found for keras>=1.1.2 (from kur)
```

Here's my setup:
```
python --version
Python 3.5.2

pip --version
ppip 9.0.1 from /Users/ben/virtualenvs/kur/lib/python3.5/site-packages (python 3.5)
```

Seems like a cool framework and would really like to try it out.

**Comment by ajsyp** [comment]
Interesting problem. Which OS are you running on? And how did you install Python (came with system, Anaconda, etc.)?

**Comment by bharris47** [comment]
Sorry for the lack of detail.  It's Mac OS running a brew installed python3.

**Comment by ajsyp** [comment]
This is odd, especially since Keras 0.1.3 was release more than 1.5 years ago... Can you report the results of `pip -vvv install kur` from within your virtual environment?

**Comment by bharris47** [comment]
Sorry @ajsyp, forgot my company had a forked version of keras in our PyPi repo. pip was simply defaulting to that version.
