### ISSUE TITLE
UnboundLocalError: local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by greatken999** [deepgram/kur#52]
error info:
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2aeb78884a90>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 582, in __del__
UnboundLocalError: local variable 'status' referenced before assignment

kur version 0.5.1

**Comment by ajsyp** [comment]
Yep, @antho-rousseau is right. See tensorflow/tensorflow#3388 for details. However, it is entirely benign and won't affect any of your training / testing / inference.
