### ISSUE TITLE
dataset file checksum fail

### ISSUE THREAD

**Issue by cogmeta** [deepgram/kur#70]
Md5 checksum is failing on all four dataset files. 

ganga$md5 lsc100-10p-train.tar.gz 
MD5 (lsc100-10p-train.tar.gz) = 16139ef9fc3c58035ee225fc22eb95be

**Comment by ajsyp** [comment]
Kur uses SHA-256, not MD5. Does that work?

**Comment by cogmeta** [comment]
Thank you. SHA-256 check succeeds. I will dig into the code tomorrow to see why get_hash function is returning different value on my system resulting in 'integrity check failed.' . I Will reopen if I need further help. Thanks again.
