### ISSUE TITLE
warning: divided by zero when `plot_hook.py` is executed using pytorch backend 

### ISSUE THREAD

**Issue by EmbraceLife** [deepgram/kur#76]
Whenever I run `kur train ` with `hooks: plot` in keras backend, everything is fine; but in pytorch backend, I got the following warning: 
```
[WARNING 2017-05-08 18:04:00,276 py.warnings _showwarnmsg:99] /Users/Natsume/Documents/kur_experiment/kur/model/hooks/plot_hook.py:287: RuntimeWarning: divide by zero encountered in true_divide
  throughput = numpy.diff(batch) / numpy.diff(time)
```
should we be worry about this?

**Comment by ajsyp** [comment]
This is entirely benign and can be ignored. It will be suppressed in a future commit.
