### ISSUE TITLE
CNTK 2 Support planned? (just like keras)

### ISSUE THREAD

**Issue by X4** [deepgram/kur#82]
Hi,

is there support planned for Microsoft's [CNTK](https://github.com/Microsoft/CNTK)?
Keras also started supporting the CNTK deep-learning toolkit.

**Comment by ajsyp** [comment]
At Deepgram, we don't have any immediate plan to support it. If Keras does, in fact, add it as a first-class citizen (like Theano / TensorFlow), then it _should_ be really easy for add support in Kur. But at the moment, we are looking to the community for a CNTK contribution to Kur.
