### ISSUE TITLE
How to save the trained weight? 

### ISSUE THREAD

**Issue by faruk-cse** [deepgram/kur#84]
We are using kur for training a speech model. But after the training finishes, no weights are stored. 
However we have tried with: 
weights: path
and 
also with this format, 
weights: 
    initial: path
    save_best: path
    last: path

but at the end of the training it just create a directory, no weight file is generated. What could be the problem and the solution. Any help would be highly appreciated.
TIA

**Comment by ajsyp** [comment]
Are you sure the weights directory is empty? The individual weight files may have been saved with a leading period ("."), making then hidden files on POSIX systems. When you `cd` into the weights directory, what does `ls -a` return?

**Comment by faruk-cse** [comment]
Let me check and get back to you. Thanks. @ajsyp

**Comment by faruk-cse** [comment]
When I do, ls -a in the weight directory I got the following output:

`..batch_normalization.0+..batch_normalization.0_beta:0.kur
..batch_normalization.0+..batch_normalization.0_gamma:0.kur
..batch_normalization.0+..batch_normalization.0_moving_mean:0.kur
..batch_normalization.0+..batch_normalization.0_moving_variance:0.kur
..batch_normalization.1+..batch_normalization.1_beta:0.kur
..batch_normalization.1+..batch_normalization.1_gamma:0.kur
..batch_normalization.1+..batch_normalization.1_moving_mean:0.kur
..batch_normalization.1+..batch_normalization.1_moving_variance:0.kur
..batch_normalization.2+..batch_normalization.2_beta:0.kur
..batch_normalization.2+..batch_normalization.2_gamma:0.kur
..batch_normalization.2+..batch_normalization.2_moving_mean:0.kur
..batch_normalization.2+..batch_normalization.2_moving_variance:0.kur
..batch_normalization.3+..batch_normalization.3_beta:0.kur
..batch_normalization.3+..batch_normalization.3_gamma:0.kur
..batch_normalization.3+..batch_normalization.3_moving_mean:0.kur
..batch_normalization.3+..batch_normalization.3_moving_variance:0.kur
..convolution.0+..convolution.0_bias:0.kur
..convolution.0+..convolution.0_kernel:0.kur
..parallel.0_..dense.0_0_0+..parallel.0_..dense.0_0_0_bias:0.kur
..parallel.0_..dense.0_0_0+..parallel.0_..dense.0_0_0_kernel:0.kur
..recurrent.0+..recurrent.0_bias:0.kur
..recurrent.0+..recurrent.0_kernel:0.kur
..recurrent.0+..recurrent.0_recurrent_kernel:0.kur
..recurrent.1+..recurrent.1_bias:0.kur
..recurrent.1+..recurrent.1_kernel:0.kur
..recurrent.1+..recurrent.1_recurrent_kernel:0.kur
..recurrent.2+..recurrent.2_bias:0.kur
..recurrent.2+..recurrent.2_kernel:0.kur
..recurrent.2+..recurrent.2_recurrent_kernel:0.kur`

So, are those the trained weights? @ajsyp

**Comment by ajsyp** [comment]
Yep! That's them.

**Comment by faruk-cse** [comment]
Thanks a lot. You really saved me from getting stuck here.  :+1:   @ajsyp

**Comment by ajsyp** [comment]
No problem! Pro-tip: if your layers are named, then the names of the saved weights will be somewhat more meaningful :)

**Comment by mahi19** [comment]
<DIR>          .
 <DIR>          ..
              0 ..batch_normalization.0+..batch_normalization.0_beta
              0 ..batch_normalization.0+..batch_normalization.0_gamma
              0 ..batch_normalization.0+..batch_normalization.0_moving_mean
              0 ..batch_normalization.0+..batch_normalization.0_moving_variance

              0 ..batch_normalization.1+..batch_normalization.1_beta
              0 ..batch_normalization.1+..batch_normalization.1_gamma
              0 ..batch_normalization.1+..batch_normalization.1_moving_mean
              0 ..batch_normalization.1+..batch_normalization.1_moving_variance

              0 ..batch_normalization.2+..batch_normalization.2_beta
              0 ..batch_normalization.2+..batch_normalization.2_gamma
              0 ..batch_normalization.2+..batch_normalization.2_moving_mean
              0 ..batch_normalization.2+..batch_normalization.2_moving_variance

              0 ..batch_normalization.3+..batch_normalization.3_beta
              0 ..batch_normalization.3+..batch_normalization.3_gamma
              0 ..batch_normalization.3+..batch_normalization.3_moving_mean
              0 ..batch_normalization.3+..batch_normalization.3_moving_variance

              0 ..convolution.0+..convolution.0_bias
              0 ..convolution.0+..convolution.0_kernel
              0 ..parallel.0_..dense.0_0_0+..parallel.0_..dense.0_0_0_bias
              0 ..parallel.0_..dense.0_0_0+..parallel.0_..dense.0_0_0_kernel
              0 ..recurrent.0+..recurrent.0_bias
              0 ..recurrent.0+..recurrent.0_kernel
              0 ..recurrent.0+..recurrent.0_recurrent_kernel
              0 ..recurrent.1+..recurrent.1_bias
              0 ..recurrent.1+..recurrent.1_kernel
              0 ..recurrent.1+..recurrent.1_recurrent_kernel
              0 ..recurrent.2+..recurrent.2_bias
              0 ..recurrent.2+..recurrent.2_kernel
              0 ..recurrent.2+..recurrent.2_recurrent_kernel
)              0 bytes
  30,297,563,136 bytes free

it shows 0 bytes. how to restart training with the best weights?
