### ISSUE TITLE
How to test a trained model with custom data?

### ISSUE THREAD

**Issue by faruk-cse** [deepgram/kur#85]
Thanks to the community for  helping me to train a custom model using kur for my custom dataset using examples/speech.yml . Now I have trained weights. How can I test the model using custom single audio file? Any help would be appreciated. 
TIA

**Comment by ohtangza** [comment]
I also want to know because we also have a plan to deploy in the actual system anytime soon!

**Comment by ajsyp** [comment]
Does #23 answer your questions?
