### ISSUE TITLE
Offline speech recognition on mobile

### ISSUE THREAD

**Issue by allenleein** [deepgram/kur#87]
Is there any way to use kur implement local, offline speech recognition on mobile?

**Comment by ajsyp** [comment]
I don't see why not. I think the biggest issue you'll run into is deciding what your tensor library / backend will be, and ensuring that you can compile it on mobile. I believe someone tried this before (mentioned on Gitter), but I don't know what the state of their project is.

**Comment by allenleein** [comment]
@ajsyp Thanks Adam. I will try to reach them on Gitter later :)
