### ISSUE TITLE
Readme links go to absolute paths

### ISSUE THREAD

**Issue by twocs** [deepgram/kur#9]
Currently, https://kur.deepgram.com is not responding. According to http://www.isitdownrightnow.com/kur.deepgram.com.html, the site has been down for a few hours. This breaks the documentation because when I'm reading https://github.com/deepgram/kur/Readme.rst the link to https://kur.deepgram.com/troubleshooting is dead.

My expectation is that the links should be relative, so that if you're reading the page on the deepgram website, the links would go to other pages on the deepgram website. But if you're reading the page on GitHub, they should go to other pages on GitHub.

**Comment by scottstephenson** [comment]
Nice catch! The underlying problem is that the host for the docs isn't set up for https. If you change the link to http you should be good. We'll fix up the docs and push a new version that removes the erroneous pathways.

Thanks!

**Comment by twocs** [comment]
It looks like the docs almost all use relative paths. However, some of the python also used the https address.

The kur.deepmind.com site doesn't support https, so the links from this page must use http.
In reference to https://github.com/deepgram/kur/issues/9

**Comment by ajsyp** [comment]
We are in the process of moving the documentation to an HTTPS server. This will resolve the problem. Thanks for pointing it out!

**Comment by noajshu** [comment]
[https://kur.deepgram.com](https://kur.deepgram.com) now works
